Add OGC API Styles Deep Dive
opengeospatial/ogcapi-workshop pull request #60
Opened 2024-09-11 13:28 UTC by doublebyte1

Addressing: https://github.com/opengeospatial/ogcapi-workshop/issues/59

2024-10-15 19:20 UTC, tomkralidis requested changes

2024-10-15 19:20 UTC, tomkralidis commented on workshop/content/docs/api-deep-dive/styles.md
> +The need for users and software to be able to control the visual portrayal of geospatial data was already present in the first generation of OGC Web Services. A profile of the [Web Map Service (WMS)]
In 2001, WMS 1.1.0 introduced enhanced support for styles using the Styled Layer Descriptor (SLD) standard.

2024-10-15 19:20 UTC, tomkralidis commented on workshop/content/docs/api-deep-dive/styles.md
> +OGC API - styles is designed to be combined with other OGC API Standards, in order to produce styled geospatial data.
OGC API - Styles (styles -> Styles)

2024-10-15 19:20 UTC, tomkralidis commented on workshop/content/docs/api-deep-dive/styles.md
> +These styles can be rendered by a client application, or applied directly by other OGC APIs that support styles. The example bellow shows the *Night* style, being applied by OGC API - maps.
- `s/bellow/below/g`
- `s/OGC API - maps/OGC API - Maps/g`

2024-10-15 19:20 UTC, tomkralidis commented on workshop/content/docs/api-deep-dive/styles.md
> +A basic request workflow could look like the diagram bellow, where a client requests the list of styles, and then asks for more information about a particular style, before fetching the stylesheet. I
- `s/bellow/below/g`

2024-10-15 19:20 UTC, tomkralidis commented on workshop/content/docs/api-deep-dive/styles.md
> +In the sample bellow, we request information about the *topographic* style. The full response can be retrieved using this request:
- `s/bellow/below/g`

2024-10-15 19:20 UTC, tomkralidis commented on workshop/content/docs/api-deep-dive/styles.md
> +In the example bellow, the *topographic* style is retrieved as a Mapbox stylesheet.
- `s/bellow/below/g`

2024-10-16 12:45 UTC, doublebyte1 commented
@tomkralidis thank you for the review! Hopefully these issues are fixed with my last commit.

2024-10-17 07:56 UTC, merged